In [ ]:
# Problem 3

In [2]:
import pandas as pd

In [4]:
#a. Create pop1 by using panda's read_csv( ) function, with 'pop1.csv' as the *only* parameter. Print pop1; 
#print the type of pop1; print pop1.describe().
pop1 = pd.read_csv('pop1.csv')
print(pop1)
print(type(pop1))
print(pop1.describe())


#b. The data in pop1.csv can be treated differently than it was in part a by forcing it to be a Series. (Ask yourself: what was it in part a, and why?) Use read_csv( ) with the parameters index_col='State' and squeeze = True. 
# Print pop1; print the type of pop1; print pop1.describe().
pop1 = pd.read_csv('pop1.csv', index_col='State', squeeze = True)
print(pop1)
print(type(pop1))
print(pop1.describe())

#c. Repeat part b for pop2.
pop2 = pd.read_csv('pop2.csv', index_col='State', squeeze = True)
print(pop2)
print(type(pop2))
print(pop2.describe())

#d. Create diff by subtracting pop2 from pop1. Print diff. 
# Print the NaN rows of diff. 
# Print the rows of diff that are negative – use the syntax: myseries[ myseries < 0] – that is, states that lost population.
diff = pop1 - pop2
print(diff)
print(diff[diff.isnull()])
print(diff[diff < 0])

#e. Using that syntax again, print the states whose population is over 1,000,000; 
# print the states whose difference is more than 500,000. 
# Create pct as the diff divided by pop2. Print pct; print the states where that percentage is greater than 0.1.
print(diff[diff > 1000000])
print(diff[diff > 500000])
pct   = diff / pop2
print(pct)
print(pct[pct > 0.1])

                   State  Population
0                Alabama     4785448
1                 Alaska      713906
2                Arizona     6407774
3               Arkansas     2921978
4             California    37320903
5               Colorado     5048281
6            Connecticut     3579125
7               Delaware      899595
8   District of Columbia      605085
9                Florida    18845785
10               Georgia     9711810
11                Hawaii     1363963
12                 Idaho     1570773
13              Illinois    12840762
14               Indiana     6490436
15                  Iowa     3050767
16                Kansas     2858213
17              Kentucky     4348200
18             Louisiana     4544532
19                 Maine     1327632
20              Maryland     5788642
21         Massachusetts     6566431
22              Michigan     9877535
23             Minnesota     5310843
24           Mississippi     2970536
25              Missouri     5995976
26               Montana      990722
27              Nebraska     1829536
28                Nevada     2702464
29         New Hampshire     1316777
30            New Jersey     8799624
31            New Mexico     2064588
32              New York    19400080
33        North Carolina     9574293
34          North Dakota      674710
35                  Ohio    11539327
36              Oklahoma     3759632
37                Oregon     3837532
38          Pennsylvania    12711158
39          Rhode Island     1053938
40        South Carolina     4635656
41          South Dakota      816165
42             Tennessee     6355301
43                 Texas    25242679
44                  Utah     2775334
45               Vermont      625880
46              Virginia     8023680
47            Washington     6742902
48         West Virginia     1854214
49             Wisconsin     5690479
50               Wyoming      564483
51           Puerto Rico     3721525
<class 'pandas.core.frame.DataFrame'>
         Population
count  5.200000e+01
mean   6.020146e+06
std    6.778635e+06
min    5.644830e+05
25%    1.764845e+06
50%    4.092866e+06
75%    6.610549e+06
max    3.732090e+07
State
Alabama                  4785448
Alaska                    713906
Arizona                  6407774
Arkansas                 2921978
California              37320903
Colorado                 5048281
Connecticut              3579125
Delaware                  899595
District of Columbia      605085
Florida                 18845785
Georgia                  9711810
Hawaii                   1363963
Idaho                    1570773
Illinois                12840762
Indiana                  6490436
Iowa                     3050767
Kansas                   2858213
Kentucky                 4348200
Louisiana                4544532
Maine                    1327632
Maryland                 5788642
Massachusetts            6566431
Michigan                 9877535
Minnesota                5310843
Mississippi              2970536
Missouri                 5995976
Montana                   990722
Nebraska                 1829536
Nevada                   2702464
New Hampshire            1316777
New Jersey               8799624
New Mexico               2064588
New York                19400080
North Carolina           9574293
North Dakota              674710
Ohio                    11539327
Oklahoma                 3759632
Oregon                   3837532
Pennsylvania            12711158
Rhode Island             1053938
South Carolina           4635656
South Dakota              816165
Tennessee                6355301
Texas                   25242679
Utah                     2775334
Vermont                   625880
Virginia                 8023680
Washington               6742902
West Virginia            1854214
Wisconsin                5690479
Wyoming                   564483
Puerto Rico              3721525
Name: Population, dtype: int64
<class 'pandas.core.series.Series'>
count    5.200000e+01
mean     6.020146e+06
std      6.778635e+06
min      5.644830e+05
25%      1.764845e+06
50%      4.092866e+06
75%      6.610549e+06
max      3.732090e+07
Name: Population, dtype: float64
State
Alabama                  4903185
Alaska                    731545
Arizona                  7278717
Arkansas                 3017804
California              39512223
Colorado                 5758736
Connecticut              3565287
Delaware                  973764
District of Columbia      705749
Florida                 21477737
Georgia                 10617423
Hawaii                   1415872
Idaho                    1787065
Illinois                12671821
Indiana                  6732219
Iowa                     3155070
Kansas                   2913314
Kentucky                 4467673
Louisiana                4648794
Maine                    1344212
Maryland                 6045680
Massachusetts            6892503
Michigan                 9986857
Minnesota                5639632
Mississippi              2976149
Missouri                 6137428
Montana                  1068778
Nebraska                 1934408
Nevada                   3080156
New Hampshire            1359711
New Jersey               8882190
New Mexico               2096829
New York                19453561
North Carolina          10488084
North Dakota              762062
Ohio                    11689100
Oklahoma                 3956971
Oregon                   4217737
Pennsylvania            12801989
Rhode Island             1059361
South Carolina           5148714
South Dakota              884659
Tennessee                6829174
Texas                   28995881
Utah                     3205958
Vermont                   623989
Virginia                 8535519
Washington               7614893
West Virginia            1792147
Wisconsin                5822434
Wyoming                   578759
Name: Population, dtype: int64
<class 'pandas.core.series.Series'>
count    5.100000e+01
mean     6.436069e+06
std      7.360660e+06
min      5.787590e+05
25%      1.789606e+06
50%      4.467673e+06
75%      7.446805e+06
max      3.951222e+07
Name: Population, dtype: float64
State
Alabama                 -117737.0
Alaska                   -17639.0
Arizona                 -870943.0
Arkansas                 -95826.0
California             -2191320.0
Colorado                -710455.0
Connecticut               13838.0
Delaware                 -74169.0
District of Columbia    -100664.0
Florida                -2631952.0
Georgia                 -905613.0
Hawaii                   -51909.0
Idaho                   -216292.0
Illinois                 168941.0
Indiana                 -241783.0
Iowa                    -104303.0
Kansas                   -55101.0
Kentucky                -119473.0
Louisiana               -104262.0
Maine                    -16580.0
Maryland                -257038.0
Massachusetts           -326072.0
Michigan                -109322.0
Minnesota               -328789.0
Mississippi               -5613.0
Missouri                -141452.0
Montana                  -78056.0
Nebraska                -104872.0
Nevada                  -377692.0
New Hampshire            -42934.0
New Jersey               -82566.0
New Mexico               -32241.0
New York                 -53481.0
North Carolina          -913791.0
North Dakota             -87352.0
Ohio                    -149773.0
Oklahoma                -197339.0
Oregon                  -380205.0
Pennsylvania             -90831.0
Puerto Rico                   NaN
Rhode Island              -5423.0
South Carolina          -513058.0
South Dakota             -68494.0
Tennessee               -473873.0
Texas                  -3753202.0
Utah                    -430624.0
Vermont                    1891.0
Virginia                -511839.0
Washington              -871991.0
West Virginia             62067.0
Wisconsin               -131955.0
Wyoming                  -14276.0
Name: Population, dtype: float64
State
Puerto Rico   NaN
Name: Population, dtype: float64
State
Alabama                 -117737.0
Alaska                   -17639.0
Arizona                 -870943.0
Arkansas                 -95826.0
California             -2191320.0
Colorado                -710455.0
Delaware                 -74169.0
District of Columbia    -100664.0
Florida                -2631952.0
Georgia                 -905613.0
Hawaii                   -51909.0
Idaho                   -216292.0
Indiana                 -241783.0
Iowa                    -104303.0
Kansas                   -55101.0
Kentucky                -119473.0
Louisiana               -104262.0
Maine                    -16580.0
Maryland                -257038.0
Massachusetts           -326072.0
Michigan                -109322.0
Minnesota               -328789.0
Mississippi               -5613.0
Missouri                -141452.0
Montana                  -78056.0
Nebraska                -104872.0
Nevada                  -377692.0
New Hampshire            -42934.0
New Jersey               -82566.0
New Mexico               -32241.0
New York                 -53481.0
North Carolina          -913791.0
North Dakota             -87352.0
Ohio                    -149773.0
Oklahoma                -197339.0
Oregon                  -380205.0
Pennsylvania             -90831.0
Rhode Island              -5423.0
South Carolina          -513058.0
South Dakota             -68494.0
Tennessee               -473873.0
Texas                  -3753202.0
Utah                    -430624.0
Virginia                -511839.0
Washington              -871991.0
Wisconsin               -131955.0
Wyoming                  -14276.0
Name: Population, dtype: float64
Series([], Name: Population, dtype: float64)
Series([], Name: Population, dtype: float64)
State
Alabama                -0.024012
Alaska                 -0.024112
Arizona                -0.119656
Arkansas               -0.031754
California             -0.055459
Colorado               -0.123370
Connecticut             0.003881
Delaware               -0.076167
District of Columbia   -0.142634
Florida                -0.122543
Georgia                -0.085295
Hawaii                 -0.036662
Idaho                  -0.121032
Illinois                0.013332
Indiana                -0.035914
Iowa                   -0.033059
Kansas                 -0.018914
Kentucky               -0.026742
Louisiana              -0.022428
Maine                  -0.012334
Maryland               -0.042516
Massachusetts          -0.047308
Michigan               -0.010947
Minnesota              -0.058300
Mississippi            -0.001886
Missouri               -0.023047
Montana                -0.073033
Nebraska               -0.054214
Nevada                 -0.122621
New Hampshire          -0.031576
New Jersey             -0.009296
New Mexico             -0.015376
New York               -0.002749
North Carolina         -0.087127
North Dakota           -0.114626
Ohio                   -0.012813
Oklahoma               -0.049871
Oregon                 -0.090144
Pennsylvania           -0.007095
Puerto Rico                  NaN
Rhode Island           -0.005119
South Carolina         -0.099648
South Dakota           -0.077424
Tennessee              -0.069390
Texas                  -0.129439
Utah                   -0.134320
Vermont                 0.003031
Virginia               -0.059966
Washington             -0.114511
West Virginia           0.034633
Wisconsin              -0.022663
Wyoming                -0.024667
Name: Population, dtype: float64
Series([], Name: Population, dtype: float64)